/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab4j;

import expression.ReadExp;
import expression.exp;
import javax.swing.JFrame;

/**
 *
 * @author Denisa
 */
public class ExpDialog extends javax.swing.JDialog {

    /**
     * Creates new form ExpDialog
     */
    public ExpDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }
    private exp exp;

    public exp get_exp(){return exp;}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Constant = new javax.swing.JButton();
        variableButton = new javax.swing.JButton();
        Arithmetic = new javax.swing.JButton();
        boolButton = new javax.swing.JButton();
        ReadButton = new javax.swing.JButton();
        readh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Constant.setText("Constant");
        Constant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConstantActionPerformed(evt);
            }
        });

        variableButton.setText("Variable");
        variableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                variableButtonActionPerformed(evt);
            }
        });

        Arithmetic.setText("Arithmetic");
        Arithmetic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArithmeticActionPerformed(evt);
            }
        });

        boolButton.setText("Boolean");
        boolButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boolButtonActionPerformed(evt);
            }
        });

        ReadButton.setText("Read");
        ReadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadButtonActionPerformed(evt);
            }
        });

        readh.setText("Read Heap");
        readh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Constant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(variableButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Arithmetic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boolButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReadButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(readh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(281, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Constant)
                .addGap(18, 18, 18)
                .addComponent(variableButton)
                .addGap(18, 18, 18)
                .addComponent(Arithmetic)
                .addGap(18, 18, 18)
                .addComponent(boolButton)
                .addGap(18, 18, 18)
                .addComponent(ReadButton)
                .addGap(18, 18, 18)
                .addComponent(readh)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConstantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConstantActionPerformed
        // TODO add your handling code here:
        ConstDialog cons=new ConstDialog((JFrame)this.getParent(),true);
        cons.setVisible(true);
        exp=cons.get_exp();
        this.dispose();
    }//GEN-LAST:event_ConstantActionPerformed

    private void variableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_variableButtonActionPerformed
        // TODO add your handling code here:
        VarDialog var=new VarDialog((JFrame)this.getParent(),true);
        var.setVisible(true);
        exp=var.get_exp();
        this.dispose();
    }//GEN-LAST:event_variableButtonActionPerformed

    private void ArithmeticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArithmeticActionPerformed
        // TODO add your handling code here:
        ArmDialog arm=new ArmDialog((JFrame)this.getParent(),true);
        arm.setVisible(true);
        exp=arm.get_exp();
        this.dispose();
    }//GEN-LAST:event_ArithmeticActionPerformed

    private void boolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boolButtonActionPerformed
        // TODO add your handling code here:
        BoolDialog arm=new BoolDialog((JFrame)this.getParent(),true);
        arm.setVisible(true);
        exp=arm.get_exp();
        this.dispose();
    }//GEN-LAST:event_boolButtonActionPerformed

    private void ReadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadButtonActionPerformed
        // TODO add your handling code here:
//        ReadDialog rd=new ReadDialog((JFrame)this.getParent(),true);
//        rd.setVisible(true);
//        exp=rd.get_exp();
        exp=new ReadExp();
        this.dispose();
    }//GEN-LAST:event_ReadButtonActionPerformed

    private void readhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readhActionPerformed
        // TODO add your handling code here:
        ReadhDialog d=new ReadhDialog((JFrame)this.getParent(),true);
        d.setVisible(true);
        exp=d.get_exp();
        this.dispose();
    }//GEN-LAST:event_readhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExpDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ExpDialog dialog = new ExpDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Arithmetic;
    private javax.swing.JButton Constant;
    private javax.swing.JButton ReadButton;
    private javax.swing.JButton boolButton;
    private javax.swing.JButton readh;
    private javax.swing.JButton variableButton;
    // End of variables declaration//GEN-END:variables
}
